apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-pod
  template:
    metadata:
      labels:
        app: myapp-pod
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.14.2
        ports:
          - containerPort: 80
        env:
          - name: NGINX_PORT
            value: "80"
          - name: NGINX_LISTEN
            value: "0.0.0.0"
      - name: multitool-container
        image: wbitt/network-multitool
        ports: 
          - containerPort: 1180
            name: http-port
          - containerPort: 11443
            name: https-port
        env:
          - name: HTTP_PORT
            value: "1180"
          - name: HTTPS_PORT
            value: "11443"